[colors]
cursor = { cursor = "#e0c69f" }

[colors.normal]
black = "#4e614f"
red = "#91362a"
green = "#858780"
yellow = "#cf9b53"
blue = "#bf7763"
magenta = "#527763"
cyan = "#7eb45f"
white = "#d9d9d9"

[colors.bright]
black = "#4e614f"
red = "#91362a"
green = "#858780"
yellow = "#cf9b53"
blue = "#bf7763"
magenta = "#527763"
cyan = "#7eb45f"
white = "#d9d9d9"

[colors.primary]
background = "#333333"
foreground = "#e0c69f"

[font]
builtin_box_drawing = true
size = 8.5

[font.bold]
family = "JetBrainsMono NF"
style="Bold"

[font.bold_italic]
family = "JetBrainsMono NF"
style = "SemiBold Italic"

[font.italic]
family = "JetBrainsMono NF"
style = "Medium Italic"

[font.normal]
family = "JetBrainsMono NF"
style = "Medium"

[window]
decorations = "none"
dynamic_padding = true
opacity = 0.95

[cursor]
style = {shape = "Block", blinking = "Never"}


[window.padding]
x = 0
y = 0
