[colors.normal]
black = "#4e614f"
red = "#91362a"
green = "#858780"
yellow = "#cf9b53"
blue = "#bf7763"
magenta = "#527763"
cyan = "#7eb45f"
white = "#d9d9d9"

[colors.bright]
black = "#4e614f"
red = "#91362a"
green = "#858780"
yellow = "#cf9b53"
blue = "#bf7763"
magenta = "#527763"
cyan = "#7eb45f"
white = "#d9d9d9"

[colors.primary]
background = "#333333"
foreground = "#e0c69f"

[font]
builtin_box_drawing = true
size = 12.0

[font.bold]
family = "JetBrainsMono NF Medium"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono NF Medium"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono NF Medium"
style = "Italic"

[font.normal]
family = "JetBrainsMono NF Medium"

[window]
decorations = "none"
dynamic_padding = true
opacity = 0.95

[window.padding]
x = 0
y = 0
