[colors.bright]
black = "#64727d"
blue = "#d4425a"
cyan = "#7eb45f"
green = "#858780"
magenta = "#527763"
red = "#ec53b0"
white = "#d9d9d9"
yellow = "#bc8f2e"

[colors.normal]
black = "#e0c69f"
blue = "#d4425a"
cyan = "#7eb45f"
green = "#858780"
magenta = "#527763"
red = "#ec53b0"
white = "#d9d9d9"
yellow = "#bc8f2e"

[colors.primary]
background = "#333333"
foreground = "#e0c69f"

[font]
builtin_box_drawing = true
size = 8.0

[font.bold]
family = "Jetbrains Mono"
style = "Bold"

[font.bold_italic]
family = "Jetbrains Mono"
style = "Bold Italic"

[font.italic]
family = "Jetbrains Mono"
style = "Italic"

[font.normal]
family = "Jetbrains Mono Semibold"

[window]
decorations = "none"
dynamic_padding = true
opacity = 0.95

[window.padding]
x = 0
y = 0
