#! /bin/bash


bspc monitor -d α β γ δ ε


bspc config border_width         3
bspc config window_gap          12
bspc config single_monocle true
bspc config focused_border_color "#E0C69F"
bspc config normal_border_color "#333333"
bspc config presel_feedback_color "#752F20"
bspc config focus_follows_pointer true


bspc config split_ratio          0.5
bspc config borderless_monocle   false
bspc config gapless_monocle      true
bspc config ignore_ewmh_focus true

bspc rule -a zen desktop='^2' follow=false 
bspc rule -a zen desktop='^2' follow=false 
bspc rule -a telegram-desktop desktop='^3' follow=false
bspc rule -a TelegramDesktop desktop='^3' follow=false
bspc rule -a "draw.io" desktop='^4' follow=false
bspc rule -a "feh" state=floating
bspc rule -a *:*:gsimplecal state=floating rectangle=314x220+803+811
bspc rule -a pavucontrol state=floating rectangle=650x400+1064+638
bspc rule -a htop state=floating rectangle=850x600+1064+438
bspc rule -a Thunar state=floating rectangle=800x600+0+0 center=true

# ~/dotfiles/scripts/startup.fish
xsetroot -cursor_name left_ptr &
xinput set-prop "DELL0A77:00 06CB:CE26 Touchpad" "libinput Tapping Enabled" 1
xinput set-prop "DELL0A77:00 06CB:CE26 Touchpad" "libinput Natural Scrolling Enabled" 1
setxkbmap -option grp:win_space_toggle us,ru    
setxkbmap -option ctrl:swapcaps
libinput-gestures-setup restart
feh --bg-fill ~/dotfiles/wallpapers/kanagawa_light.jpg
