#! /bin/sh


bspc monitor -d α β γ δ ε

bspc config border_width         2
bspc config window_gap          12
bspc config focused_border_color "#E0C69F"
bspc config normal_border_color "#555555"
bspc config presel_feedback_color "#752F20"
bspc config focus_follows_pointer true

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a firefox desktop='^2'
bspc rule -a Pavucontrol state=floating rectangle=650x400+1254+44
bspc rule -a htop state=floating rectangle=850x600+1054+44
    # $mod+period exec pactl set-source-volume @DEFAULT_SOURCE@ +5%
    # $mod+comma exec pactl set-source-volume @DEFAULT_SOURCE@ -5%

feh --bg-scale ~/Pictures/wallpapers/reversal-red.jpg
xinput set-prop "GXTP7863:00 27C6:01E0 Touchpad" "libinput Tapping Enabled" 1
xinput set-prop "GXTP7863:00 27C6:01E0 Touchpad" "libinput Natural Scrolling Enabled" 1
setxkbmap -option grp:alt_shift_toggle us,ru    # Смена языка. Такой подход не совсем "правильный"
libinput-gestures-setup restart
polybar -r
