#!/bin/bash


swaylock --effect-blur 5x3 --clock --time-color="#e0c69f" --date-color="#e0c69f" --verif-color="#e0c69f"\
    --keylayout 1 --layout-color="#e0c69f" \
    --ring-color="#000000" --inside-color="#000000" --insidever-color="#000000" --ringver-color="#000000" \
    --insidewrong-color="#752f20" --ringwrong-color="#752f20" --indicator
